//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1612018_FinalProject.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATHANG
    {
        public int MaDH { get; set; }
        public string MaSP { get; set; }
        public string MaLoai { get; set; }
        public int SoLuong { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public string TenKH { get; set; }
        public string Sdt { get; set; }
        public Nullable<double> TienThu { get; set; }
        public Nullable<int> MaEvent { get; set; }
        public string DiaChi { get; set; }
        public Nullable<double> TraTruoc { get; set; }
        public Nullable<int> HinhThuc { get; set; }
        public string GhiChu { get; set; }
    
        public virtual LOAI LOAI { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
