//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1612018_FinalProject.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MaHD { get; set; }
        public string MaSP { get; set; }
        public string MaLoai { get; set; }
        public int SoLuong { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        public Nullable<double> TienThu { get; set; }
        public Nullable<int> MaEvent { get; set; }
        public Nullable<int> HinhThuc { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
